
FROM dustynv/ros:melodic-ros-base-l4t-r32.7.1

ENV DEBIAN_FRONTEND=noninteractive

# Install ROS tools and Python3
RUN apt-get update && apt-get install -y \
    ros-melodic-sensor-msgs \
    ros-melodic-rospy \
    ros-melodic-cv-bridge \
    python3-pip \
    python3-opencv \
    libgl1-mesa-glx \
    librealsense2-utils \
    librealsense2-dev \
    && rm -rf /var/lib/apt/lists/*

# Install pyrealsense2 via pip
RUN pip3 install pyrealsense2

# Create a workspace directory
WORKDIR /workspace
COPY . /workspace

# Set default command to run your script
CMD ["python3", "pointcloud.py"]
